### PR TITLE
Add suse packaging setup.

### PR DESCRIPTION
**Pull request by smarlowucf**

### CODE REVIEW

**Comment by shihuazhang** [comment]
Hi smarlowucf,

Thanks for your contribution.
There are a little bit more work required for supporting other Linux distributions. You can refer to the FreeBSD support we added very recently.

https://github.com/aws/amazon-ssm-agent/pull/18
https://github.com/aws/amazon-ssm-agent/pull/20
https://github.com/aws/amazon-ssm-agent/pull/23

Once you have them ready, we will merge the code to the internal repository and have them reviewed

**Comment by shihuazhang** [comment]
Actually it's better to refer to the reviewed commit.

https://github.com/aws/amazon-ssm-agent/commit/99d966309cbbac407d46926f134333d4efb15636

Please let me know if you have any question.

**Comment by smarlowucf** [comment]
Thanks @shihuazhang. Looking at the PR I'm adding a check for os-release in the getPlatformDetails method. Right now I have the build requiring lsb-release but os-release is the more standard way to do so. I think this is the only change necessary for SUSE.

I will commit the change and cleanup the commit history.

**Comment by shihuazhang** [comment]
Hi smarlowucf,

Thanks for the changes, due to the size of the commits, we will have to get them reviewed by the open source team. We might have to merge them internally so we can test the change with our internal tests.

Also, could you please confirm this contribution is under the terms of the Apache 2.0 license?

Many Thanks

**Comment by smarlowucf** [comment]
@shihuazhang Yes it is under terms of Apache 2.0 license.

**Comment by mmendonca3** [comment]
Hello smarlowucf, 

After an internal review, we have come to a conclusion that unfortunately, we cannot include all your changes in our product. Some of changes seem to have been duplicated (the conf, service and spec files). We encourage you to use the existing spec files and makefiles to build your rpm. You can go over the existing documentation. Also, feel free to reach out to us if you have any concerns/questions.

Will it be okay to include only the changes made in platform_unix.go? 

Thank you!

**Comment by smarlowucf** [comment]
Hi @mmendonca3, can you expand more on the duplicated files? The spec is very different from the existing linux and amazon-linux spec files.

**Comment by mmendonca3** [comment]
Hi smarlwucf, 

We have a single method to package all linux based agents and want to continue keeping the consistency. Since the RPM created by the makefile in amazon-ssm-agent can be used to create an agent which will be functional on SUSE, we think that adding additional options (.conf, .service and .spec files) will be duplicating the effort. If you believe there are changes made in your commit that must be added into the existing spec files (packaging/linux/amazon-ssm-agent.spec) that we use for linux packages, please let us know and we can work with you to making sure we make that available. 
Along with this, we are unable to distribute the file -  packaging/suse/amazon-ssm-agent.spec with SUSE licenses ( for your reference - "Copyright (c) 2017 SUSE LINUX GmbH, Nuernberg, Germany.") 

Thank you!

**Comment by smarlowucf** [comment]
Thank you for the info @mmendonca3. You can indeed incorporate the changes in platform_unix.go.

**Pull request closed without merging**
