### PR TITLE
Update version to latest release.

### PR DESCRIPTION
**Pull request by smarlowucf**
Version is now 2.0.633.0

### CODE REVIEW

**Comment by copumpkin** [comment]
👍 my 2.0.633.0 is misreporting its version to the console right now

**Comment by shihuazhang** [comment]
hi smarlowucf, 

The build number such as 633 is generated by our internal build tool automatically during the build process. We don't change the build number manually.

If you are managing your own build process base on our code release, you may want to consider automating version update in your build script.

Here are the files you need to update
https://github.com/aws/amazon-ssm-agent/blob/master/agent/version/version.go
https://github.com/aws/amazon-ssm-agent/blob/master/VERSION

**Comment by copumpkin** [comment]
@shihuazhang my confusion is from the GitHub tags. I use the git tag which says 2.0.633.0 and it's confusing to have a tagged version that doesn't match the program's self-reported value.

I'm packaging this for a Linux distro, so are you saying I should add a little script to my build that copies the current git tag into version.go and VERSION?

**Comment by shihuazhang** [comment]
Yes, that would solve the misreporting version number issue

**Comment by smarlowucf** [comment]
I understand I can create a couple patches to fix the version to match the GitHub tags. But I'm confused why it wouldn't line up with the version number. If I package and install the agent on an instance with version as 2.0.0.0 it reports the agent is not up to date. Via the command:

`aws ssm describe-instance-information --output text --query "InstanceInformationList[*]"`

However, patching the version in the build, reports version 2.0.633.0 as latest. So it appears to be verifying this version against AWS.

Why would the GitHub tag be 2.0.633.0 and AWS verify that as latest yet the internal build be 2.0.0.0? The latest version value I'm referencing is from the CLI http://docs.aws.amazon.com/ssm/latest/APIReference/API_InstanceInformation.html#EC2-Type-InstanceInformation-IsLatestVersion.

**Comment by smarlowucf** [comment]
To simplify my question, why would the version info referenced by the agent in the code not match the actual version of the release?

**Comment by shihuazhang** [comment]
Hi smarlowucf

The Version file will be modified automatically during our internal build.
However, the version files will not be checked in as it will trigger another build.

To simplify, we controls the major and minor version such as 2.0, the internal build tool decide what the build number is such as the 633.

**Comment by smarlowucf** [comment]
Okay, thanks for the explanation.

**Pull request closed without merging**
