### PR TITLE
fix go version number

### PR DESCRIPTION
**Pull request by chefren**
*Description of changes:*

Fixing problem with travis build go version definition

https://travis-ci.org/github/aws/amazon-ssm-agent/builds/672657397

Go version 1.12.0 is not in the releases, should use 1.12 or 1.12.x ([ref](https://docs.travis-ci.com/user/languages/go/#specifying-a-go-version-to-use))

https://golang.org/dl/

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by chefren** [comment]
Hi @shihuazhang are you able to review please? I don't have permissions to add reviewers

Kind regards

**Comment by chefren** [comment]
Looks like some other error now

```
2020/05/01 04:07:39 Failed to load instance info from vault. Failed to create vault folder. failed to create directory /var/lib/amazon/ssm/Vault/Store. mkdir /var/lib/amazon: permission denied
Info: Downloading S3 artifacts from path -  https://s3.amazonaws.com/my-bucket/mydummyfolder/file.rb
Debug: File URL -  https://s3.amazonaws.com/my-bucket/mydummyfolder/file.rb
Debugf: https://s3.amazonaws.com/my-bucket/mydummyfolder/file.rb is valid s3 url
Debug: S3 object -  {Region: us-east-1; Bucket: my-bucket; Key: mydummyfolder/file.rb; IsValidS3URI: true; IsPathStyle: true}
Error: Cannot get the current instance region information
--- FAIL: TestS3Resource_Download (0.00s)
panic: 
```

**Comment by chefren** [comment]
Also missing region argument value in a mock call

```
mock: Unexpected Method Call
ListS3Directory(*log.Mock,s3util.AmazonS3URL)
...
		1: s3util.AmazonS3URL{IsValidS3URI:true, IsPathStyle:true, Bucket:"my-bucket", Key:"mydummyfolder/file.rb", Region:""}
The closest call I have is: 
ListS3Directory(*log.Mock,s3util.AmazonS3URL)
...
		1: s3util.AmazonS3URL{IsValidS3URI:true, IsPathStyle:true, Bucket:"my-bucket", Key:"mydummyfolder/file.rb", Region:"us-east-1"}

```

**Comment by chefren** [comment]
This is perhaps the root cause

`2020/05/01 04:07:39 Failed to load instance info from vault. Failed to create vault folder. failed to create directory /var/lib/amazon/ssm/Vault/Store. mkdir /var/lib/amazon: permission denied
`

**Comment by chefren** [comment]
Hi @ferkhat-amz , are you able to review please? I don't have permissions to add reviewers

Thanks!

**Comment by chefren** [comment]
I see the build succeeded last time around 2 years ago!
https://travis-ci.org/github/aws/amazon-ssm-agent/builds/427910307

**Comment by ferkhat-amz** [comment]
Thanks for reaching out to us. We will look into this request.

**Comment by ferkhat-aws** [comment]
The issue has been addressed by our team. No longer need to pull this request. 
Closing.

**Comment by chefren** [comment]
Apparently an error check was missing removal?

https://github.com/aws/amazon-ssm-agent/commit/3bb2ee6b3522002795e5cf64b9f1a024627e1a3b

**Pull request closed without merging**
