### PR TITLE
Add Support for AlmaLinux OS

### LINKED ISSUE #447: Add Support for AlmaLinux OS
The Amazon SSM Agent is installed and enabled on `x86_64` and `AArch64` of AlmaLinux OS 8 and 9 [Community](https://wiki.almalinux.org/cloud/AWS.html) and [Marketplace](https://aws.amazon.com/marketplace/seller-profile?id=529d1014-352c-4bed-8b63-6120e4bd3342) AMIs. It would be nice to have the complete integration. The support also needed for some OS specific documents i.e. `AWS-RunPatchBaseline`(`patch-baseline-operations-1.86`) and `AWS-UpdateSSMAgent`

https://bugs.almalinux.org/view.php?id=234

### PR DESCRIPTION
**Pull request by LKHN**
Signed-off-by: Elkhan Mammadli <elkhan.mammadli@protonmail.com>

Resolves: #447 

*Description of changes:*

Add Support for AlmaLinux OS

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by srbala — APPROVED** [review]
LGTM

**Comment by srbala** [comment]
@VishnuKarthikRavindran This PR adds AlmaLinux support

**Review by srbala — APPROVED** [review]

**Comment by Kamibjj** [comment]
Hello, 

hello, i'm having this bug with Alma Linux and the AWS SSM Agent where the OS can't be identified. These changes come in handy. I see that the push was validated, is the pull gonna ever be validated and released? thank you.

**Comment by aquiles2k** [comment]
Hi, when will this be merged?

**Comment by gianniLesl** [comment]
Done

**Pull request closed without merging**
